package com.example.settings.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy

internal class SettingsCodeGenerator(
    private val kspCodeGenerator: CodeGenerator,
    @Suppress("unused") private val logger: KSPLogger
) {
    // Common types
    private val flowType = ClassName("kotlinx.coroutines.flow", "Flow")
    private val prefsType = ClassName("androidx.datastore.preferences.core", "Preferences")
    private val dataStoreType = ClassName("androidx.datastore.core", "DataStore").parameterizedBy(prefsType)
    private val contextType = ClassName("android.content", "Context")

    // ----- Store generation -----

    fun generateStore(
        packageName: String,
        interfaceName: String,
        groupName: String,
        settings: List<SettingInfo>
    ) {
        val storeName = "${interfaceName}Store"
        val fileSpec = FileSpec.builder(packageName, storeName)
            .addFileComment("DO NOT EDIT — Generated by settings-processor KSP")
            .addType(buildStoreTypeSpec(storeName, groupName, settings))
            .build()

        kspCodeGenerator.createNewFile(
            dependencies = Dependencies(false),
            packageName = packageName,
            fileName = storeName
        ).bufferedWriter().use { fileSpec.writeTo(it) }
    }

    private fun buildStoreTypeSpec(
        storeName: String,
        groupName: String,
        settings: List<SettingInfo>
    ): TypeSpec {
        val namedAnnotation = AnnotationSpec.builder(ClassName("javax.inject", "Named"))
            .addMember("%S", groupName)
            .build()

        val constructor = FunSpec.constructorBuilder()
            .addAnnotation(ClassName("javax.inject", "Inject"))
            .addParameter(
                ParameterSpec.builder("dataStore", dataStoreType)
                    .addAnnotation(namedAnnotation)
                    .build()
            )
            .build()

        val builder = TypeSpec.classBuilder(storeName)
            .primaryConstructor(constructor)
            .addProperty(
                PropertySpec.builder("dataStore", dataStoreType, KModifier.PRIVATE)
                    .initializer("dataStore")
                    .build()
            )

        // Key constants
        settings.forEach { setting ->
            builder.addProperty(buildKeyProperty(setting))
        }

        // Flow properties
        settings.forEach { setting ->
            builder.addProperty(buildFlowProperty(setting))
        }

        // Suspend setters
        settings.forEach { setting ->
            builder.addFunction(buildSetterFunction(setting))
        }

        return builder.build()
    }

    private fun buildKeyProperty(setting: SettingInfo): PropertySpec {
        val keyFnName = when (setting.type) {
            SettingType.STRING -> "stringPreferencesKey"
            SettingType.INT -> "intPreferencesKey"
            SettingType.LONG -> "longPreferencesKey"
            SettingType.FLOAT -> "floatPreferencesKey"
            SettingType.BOOL -> "booleanPreferencesKey"
        }
        val keyMember = MemberName("androidx.datastore.preferences.core", keyFnName)
        // Preferences.Key<T>
        val keyType = ClassName("androidx.datastore.preferences.core", "Preferences", "Key")
            .parameterizedBy(kotlinTypeFor(setting.type))
        return PropertySpec.builder(keyConstName(setting.propName), keyType, KModifier.PRIVATE)
            .initializer("%M(%S)", keyMember, setting.key)
            .build()
    }

    private fun buildFlowProperty(setting: SettingInfo): PropertySpec {
        val kotlinType = kotlinTypeFor(setting.type)
        val flowPropType = flowType.parameterizedBy(kotlinType)
        val mapMember = MemberName("kotlinx.coroutines.flow", "map")
        val keyConst = keyConstName(setting.propName)

        val initializer = when (setting.type) {
            SettingType.STRING -> CodeBlock.of(
                "dataStore.data.%M·{·it[%N]·?:·%S·}",
                mapMember, keyConst, setting.defaultValue as String
            )
            SettingType.LONG -> CodeBlock.of(
                "dataStore.data.%M·{·it[%N]·?:·%LL·}",
                mapMember, keyConst, setting.defaultValue as Long
            )
            SettingType.FLOAT -> CodeBlock.of(
                "dataStore.data.%M·{·it[%N]·?:·%Lf·}",
                mapMember, keyConst, setting.defaultValue as Float
            )
            SettingType.INT -> CodeBlock.of(
                "dataStore.data.%M·{·it[%N]·?:·%L·}",
                mapMember, keyConst, setting.defaultValue as Int
            )
            SettingType.BOOL -> CodeBlock.of(
                "dataStore.data.%M·{·it[%N]·?:·%L·}",
                mapMember, keyConst, setting.defaultValue as Boolean
            )
        }

        return PropertySpec.builder("${setting.propName}Flow", flowPropType)
            .initializer(initializer)
            .build()
    }

    private fun buildSetterFunction(setting: SettingInfo): FunSpec {
        val editMember = MemberName("androidx.datastore.preferences.core", "edit")
        val setterName = "set${setting.propName.replaceFirstChar { it.uppercase() }}"
        val keyConst = keyConstName(setting.propName)

        return FunSpec.builder(setterName)
            .addModifiers(KModifier.SUSPEND)
            .addParameter("value", kotlinTypeFor(setting.type))
            .addStatement("dataStore.%M·{·it[%N]·=·value·}", editMember, keyConst)
            .build()
    }

    // ----- Module generation -----

    fun generateModule(
        packageName: String,
        interfaceName: String,
        groupName: String,
        @Suppress("UNUSED_PARAMETER") settings: List<SettingInfo>
    ) {
        val moduleName = "${interfaceName}Module"
        val storeName = "${interfaceName}Store"
        val storeType = ClassName(packageName, storeName)

        // Top-level DataStore extension property name: "recemotion_setup" -> "recemotionSetupDataStore"
        val extPropName = snakeToCamel(groupName) + "DataStore"

        val namedAnnotation = AnnotationSpec.builder(ClassName("javax.inject", "Named"))
            .addMember("%S", groupName)
            .build()

        // Top-level extension property: private val Context.xxxDataStore by preferencesDataStore("name")
        val prefsDataStoreMember = MemberName(
            "androidx.datastore.preferences",
            "preferencesDataStore"
        )
        val extProperty = PropertySpec.builder(extPropName, dataStoreType)
            .receiver(contextType)
            .addModifiers(KModifier.PRIVATE)
            .delegate(CodeBlock.of("%M(name·=·%S)", prefsDataStoreMember, groupName))
            .build()

        // @Provides @Singleton @Named provideDataStore function
        val provideDataStoreFn = FunSpec.builder("provide${interfaceName}DataStore")
            .addAnnotation(ClassName("dagger", "Provides"))
            .addAnnotation(ClassName("javax.inject", "Singleton"))
            .addAnnotation(namedAnnotation)
            .addParameter(
                ParameterSpec.builder("context", contextType)
                    .addAnnotation(ClassName("dagger.hilt.android.qualifiers", "ApplicationContext"))
                    .build()
            )
            .returns(dataStoreType)
            .addStatement("return·context.%N", extPropName)
            .build()

        // @Provides @Singleton provideStore function
        val provideStoreFn = FunSpec.builder("provide${interfaceName}Store")
            .addAnnotation(ClassName("dagger", "Provides"))
            .addAnnotation(ClassName("javax.inject", "Singleton"))
            .addParameter(
                ParameterSpec.builder("dataStore", dataStoreType)
                    .addAnnotation(namedAnnotation)
                    .build()
            )
            .returns(storeType)
            .addStatement("return·%T(dataStore)", storeType)
            .build()

        // Hilt @Module object
        val moduleObject = TypeSpec.objectBuilder(moduleName)
            .addAnnotation(ClassName("dagger", "Module"))
            .addAnnotation(
                AnnotationSpec.builder(ClassName("dagger.hilt", "InstallIn"))
                    .addMember("%T::class", ClassName("dagger.hilt.components", "SingletonComponent"))
                    .build()
            )
            .addFunction(provideDataStoreFn)
            .addFunction(provideStoreFn)
            .build()

        val fileSpec = FileSpec.builder(packageName, moduleName)
            .addFileComment("DO NOT EDIT — Generated by settings-processor KSP")
            .addProperty(extProperty)
            .addType(moduleObject)
            .build()

        kspCodeGenerator.createNewFile(
            dependencies = Dependencies(false),
            packageName = packageName,
            fileName = moduleName
        ).bufferedWriter().use { fileSpec.writeTo(it) }
    }

    // ----- Helpers -----

    private fun kotlinTypeFor(type: SettingType): ClassName = when (type) {
        SettingType.STRING -> String::class.asClassName()
        SettingType.INT -> Int::class.asClassName()
        SettingType.LONG -> Long::class.asClassName()
        SettingType.FLOAT -> Float::class.asClassName()
        SettingType.BOOL -> Boolean::class.asClassName()
    }

    /** "lastDate" -> "KEY_LAST_DATE" */
    private fun keyConstName(propName: String): String =
        "KEY_" + propName.replace(Regex("([A-Z])")) { "_${it.value}" }.uppercase()

    /** "recemotion_setup" -> "recemotionSetup" */
    private fun snakeToCamel(name: String): String =
        name.split("_").mapIndexed { i, part ->
            if (i == 0) part else part.replaceFirstChar { it.uppercase() }
        }.joinToString("")
}
